### ISSUE TITLE
IE 11 compatibility possible

### ISSUE THREAD

**Issue by capsular** [konstantinmuenster/gatsby-starter-portfolio-minimal#1]
Hi, 
I'm trying to make the theme compatible with IE 11 and Safari < 12.1 and thought the problem might be IntersectionObserver. So I added the following snippet to gatsby-browser.js:

```
export const onClientEntry = async () => {
  if (typeof IntersectionObserver === `undefined`) {
    await import(`intersection-observer`)
    console.log(`# IntersectionObserver is polyfilled!`)
  }
}
```
But that didn't help. Is it a bad idea to try and make it backwards compatible? 
Btw: this is perfect theme for me as a react newbie to understand sooo many concepts! Thanks for that.

**Comment by konstantinruge** [comment]
Hi @capsular , thanks a lot! Glad to hear that :) 

Your code looks good to me. I just tested it and it loads the polyfill properly. I updated the master branch with a working version. Please check if it works for you as well.

**Comment by capsular** [comment]
Oh, you're right! 
My site still doesn't work on IE so that means there's a problem with the code I added to your starter.. good to know!
