### ISSUE TITLE
Splash Screen Issue

### ISSUE THREAD

**Issue by tjoab** [konstantinmuenster/gatsby-starter-portfolio-minimal#11]
Hey! I have been having trouble getting the splash screen to display on the "Privacy" and "Imprint" pages. I have useSplashScreen set to true in the respective .mdx files, but alas no splash screen shows up. Any idea what might be going on here?

**Comment by konstantinruge** [comment]
Hi! Sorry for the late response. Indeed, there was an issue! I moved the SplashScreen import to the Layout component so that it will be rendered on every page if activated. My commit df71fd8676a545dd7256e70a4dfd32a60d02e27b should fix your problem 👍
