### ISSUE TITLE
how to disable Latest Articles?

### ISSUE THREAD

**Issue by humbernieto** [konstantinmuenster/gatsby-starter-portfolio-minimal#15]
Thank you very much

**Comment by konstantinruge** [comment]
Hey @husani925 ! Please have a look at my updated [Portfolio Minimal starter project](https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme). There you can choose easily which sections should be included on your page (see [example](https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme/blob/main/src/pages/index.js)).

Hope this helps 😊

**Comment by humbernieto** [comment]
Thank you very much you are the best, if I just discovered it, I like the minimalist template, I will use it for my portfolio www.humbersanchez.com

**Comment by konstantinruge** [comment]
Looks awesome 😁 I will close this issue here, have fun exploring the theme!
