### ISSUE TITLE
cross-browser design issues

### ISSUE THREAD

**Issue by chan-dev** [konstantinmuenster/gatsby-starter-portfolio-minimal#2]
The horizontal scroll  `overflow-x:scroll` for some particular sections are always showing in Firefox. 

This is a screenshot of the template .

![screenshot of image in firefox](https://user-images.githubusercontent.com/46891115/98328383-924d7180-2030-11eb-9b33-c4812b1ddfbf.png)

**Comment by konstantinruge** [comment]
Thanks for the hint! I just pushed a fix - now the scrollbar should be hidden in Firefox.
