### ISSUE TITLE
"window is not defined" 

### ISSUE THREAD

**Issue by maxgraze-zz** [konstantinmuenster/gatsby-starter-portfolio-minimal#4]
Getting this issue at build time:

<img width="646" alt="window not defined" src="https://user-images.githubusercontent.com/18546773/102672571-0017ad80-4146-11eb-9559-1747cc4de29f.png">

The odd part is I already deployed it to netflify. Anyone else come across and solved this problem? Thanks!

**Comment by konstantinruge** [comment]
Hi! 

Did you add custom code to the `layout.js` file? Cause I couldn't find the code snippet you posted.

In general, `window` is not available during build time hence it should be wrapped in an `isSSR` condition like here: https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal/blob/master/src/components/header.js#L82.

Maybe that already solves your issue?

**Comment by konstantinruge** [comment]
Closed due to inactivity.
