### ISSUE TITLE
Splash Screen not working

### ISSUE THREAD

**Issue by DzunN86** [konstantinmuenster/gatsby-starter-portfolio-minimal#5]
How do I get setup the splash screen ?
thanks

**Comment by konstantinruge** [comment]
Hi, you can enable the splash screen for each page individually in the respective markdown file. For example, if you want to enable it for the home page, set `useSplashScreen` to `true` here: https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal/blob/master/content/index/index.mdx

This will automatically set up the splash screen. Let me know if it works 👍

**Comment by DzunN86** [comment]
I see, it work, Thanks 🙌
