### ISSUE TITLE
content not showing in safari mac

### ISSUE THREAD

**Issue by XhoanaK** [konstantinmuenster/gatsby-starter-portfolio-minimal#7]
I was looking at some portfolios using gatsby and came across yours. On google everything works but when I tried to open it on safari no content was showing. Also tested your personal website https://www.konstantin.digital/ and the same issue, no content is shown. 
<img width="1440" alt="minimal_portfolio" src="https://user-images.githubusercontent.com/44309692/110727816-f3a56d00-81e9-11eb-8449-f240b98a4ab9.png">

**Comment by konstantinruge** [comment]
Hm, I cannot reproduce the error on Mac/Safari 14.0.3.😕  

Can you confirm that the error still shows up? And which version do you use?

**Comment by XhoanaK** [comment]
the error still shows and i use macOS Catalina version 10.15.4

**Comment by konstantinruge** [comment]
I just deployed a fix. Could you have a look if it works now? 👍 

Commit 060bcc4ed69774fd174b906f4e9e9da72f57523a

**Comment by XhoanaK** [comment]
I just tested it and it works 👍🏻 everything shows up.
Let me know if you're going to add the same fix in  https://www.konstantin.digital/ and you want me to check if it works 😊

**Comment by konstantinruge** [comment]
That's super nice! I just fixed the issue in konstantin.digital as well. Would be great if you could check if it works 😊

**Comment by XhoanaK** [comment]
I just checked, everything looks good on safari. 😊 Thanks for fixing this issue. ^_^

**Comment by konstantinruge** [comment]
Thanks for letting me know! 👍
