### ISSUE TITLE
Dark/Light theme not working correctly

### ISSUE THREAD

**Issue by sinedied** [konstantinmuenster/gatsby-starter-portfolio-minimal#8]
It seems that the light/dark theme switch is not working correctly, unless I missed something.

If I set my Mac to light theme and load your website after, it still use the dark theme. If I switch to the light theme with the website loaded, then it switches correctly to the light theme. But if I hits F5 to refresh the page, it changes back to the dark theme.

It seems to me that the light/dark detection isn't inferred correctly when the website loads. ~~Any idea on how to fix that?~~

EDIT: Here's a PR for the fix

**Comment by konstantinruge** [comment]
Good finding! Probably got broken while refactoring 😞  Thanks for fixing!
